version: '3.0'
services:
  postgresql:
    image: 'postgres:12.2-alpine'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'test'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'user'
    volumes:
      - './init-db.sql:/docker-entrypoint-initdb.d/init-db.sql'
